### ISSUE TITLE
Dependency conflict when installing packages

### ISSUE THREAD

**Issue by ZiadJ** [shamscorner/vitesse-stackter-clean-architect#1]
Could not resolve dependency:

vite@"^2.9.0" from @intlify/vite-plugin-vue-i18n@4.0.0

vite@"^2.0.0" from vite-plugin-vue-inspector@0.5.7

vite@"^2.5.0" from vite-plugin-vue-layouts@0.6.0

**Comment by ZiadJ** [comment]
I could work around it by removing the dependencies from package.json during the installation process to then install them separately but it's probably not something a beginner can easily figure out.

**Comment by shamscorner** [comment]
@ZiadJ I really apologize for ignoring your comment till now. I was way too busy with many things in my life recently. So I made some dependency updates on this repo. You should be able to install it correctly on your machine.

Please use,
Node version: v17.6.0 with PNPM
